# Generated by Django 3.1.5 on 2022-09-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(help_text='Ingrese nombre del proveedor', max_length=500)),
                ('direccion', models.CharField(help_text='Ingrese la direccion', max_length=500)),
                ('ruc_proveedor', models.CharField(default='-', help_text='Ingrese el ruc del proveedor', max_length=500)),
                ('telefono', models.CharField(help_text='Ingrese el telefono del proveedor', max_length=500)),
                ('email', models.EmailField(blank=True, default='-', help_text='Ingrese email del proveedor', max_length=500, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'permissions': (('add_proveedor', 'Agregar Proveedor'), ('change_proveedor', 'Editar Proveedor'), ('delete_proveedor', 'Eliminar Proveedor'), ('view_proveedor', 'Listar Proveedores')),
                'default_permissions': (),
            },
        ),
    ]
