# Generated by Django 4.1.7 on 2023-06-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_facturacompra_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='07/06/2023 21:56:25 hs', editable=False, max_length=200),
        ),
    ]
