# Generated by Django 4.1.7 on 2023-06-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_pedido_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='07/06/2023 23:00:10 hs', editable=False, max_length=200),
        ),
    ]
