# Generated by Django 4.1.7 on 2023-05-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_alta',
            field=models.CharField(default='15/05/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='15/05/2023 19:23:19 hs', max_length=500, null=True),
        ),
    ]
