# Generated by Django 3.2.9 on 2022-09-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='27/09/2022 23:50:42 hs', max_length=500, null=True),
        ),
    ]
