# Generated by Django 4.1.7 on 2023-06-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_cabeceraventa_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='07/06/2023 22:00:16 hs', max_length=500, null=True),
        ),
    ]
