# Generated by Django 4.1.7 on 2023-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_cabeceraventa_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_alta',
            field=models.CharField(default='08/06/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='08/06/2023 16:12:33 hs', max_length=500, null=True),
        ),
    ]
