# Generated by Django 4.1.7 on 2023-06-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_caja_fecha_hora_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_alta',
            field=models.CharField(default='05/06/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='05/06/2023 21:44:51 hs', max_length=500, null=True),
        ),
    ]
