# Generated by Django 4.1.7 on 2023-06-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_alter_caja_fecha_hora_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='07/06/2023 23:00:10 hs', max_length=500, null=True),
        ),
    ]
