# Generated by Django 4.1.7 on 2023-05-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_historicoproductoprecio_fecha_alta_and_more'),
        ('utiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacunasAplicadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_aplicadas', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
