# Generated by Django 4.1.7 on 2023-06-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_historicoproductoprecio_fecha_alta_and_more'),
        ('utiles', '0002_vacunasaplicadas_serviciovendido_productovendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVendidoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mes', models.IntegerField(blank=True, null=True)),
                ('label_mes', models.CharField(blank=True, max_length=500, null=True)),
                ('anho', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
