# Generated by Django 4.1.7 on 2023-06-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0003_productovendidomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovendidomes',
            name='fecha_vendido',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
