# Generated by Django 4.1.7 on 2023-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0005_remove_productovendidomes_fecha_vendido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciovendido',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
