# Generated by Django 4.1.7 on 2023-06-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0006_serviciovendido_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productovendidomes',
            name='anho',
        ),
        migrations.RemoveField(
            model_name='productovendidomes',
            name='label_mes',
        ),
        migrations.RemoveField(
            model_name='productovendidomes',
            name='numero_mes',
        ),
    ]
