# Generated by Django 4.0.4 on 2022-08-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Ingrese email del cliente', max_length=200, null=True),
        ),
    ]
