# Generated by Django 3.2.9 on 2022-08-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='25/08/2022 12:15:28 hs', editable=False, max_length=200),
        ),
    ]
