# Generated by Django 3.1.5 on 2022-10-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='05/10/2022 15:40:44 hs', editable=False, max_length=200),
        ),
    ]
