# Generated by Django 3.1.6 on 2022-09-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_tipoproducto_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='05/09/2022 17:49:12 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
