# Generated by Django 4.0.4 on 2022-09-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_tipoproducto_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='08/09/2022 21:00:59 hs', editable=False, max_length=200),
        ),
    ]
