# Generated by Django 3.1.6 on 2022-09-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20220905_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='05/09/2022 17:57:06 hs', editable=False, max_length=200),
        ),
    ]
