# Generated by Django 4.0.4 on 2022-09-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_tipoproducto_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='10/09/2022 12:32:16 hs', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(help_text='Ingrese nombre del producto', max_length=500)),
                ('descripcion', models.CharField(help_text='Ingrese descripcion del producto', max_length=500)),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_baja', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('fecha_movimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_compra', models.CharField(default='10/09/2022', editable=False, max_length=200)),
                ('precio_compra', models.CharField(blank=True, default='0', help_text='Ingrese precio de compra', max_length=500, null=True)),
                ('precio_venta', models.CharField(help_text='Ingrese precio de venta', max_length=500)),
                ('stock_minimo', models.IntegerField(help_text='Ingrese stock minimo')),
                ('lote', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.IntegerField(help_text='Ingrese stock minimo')),
                ('stock_total', models.IntegerField(blank=True, null=True)),
                ('stock_movido', models.IntegerField(blank=True, default=0, null=True)),
                ('servicio_o_producto', models.CharField(blank=True, default='P', max_length=2, null=True)),
                ('producto_vencido', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('id_servicio', models.IntegerField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
                ('tipo_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto')),
            ],
        ),
    ]
