# Generated by Django 4.1.7 on 2023-04-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_tipoproducto_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='17/04/2023 21:39:14 hs', editable=False, max_length=200),
        ),
    ]
