# Generated by Django 3.1.6 on 2022-09-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20220905_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='05/09/2022 23:36:53 hs', editable=False, max_length=200),
        ),
    ]
