# Generated by Django 4.1.7 on 2023-04-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_stock_total_alter_tipoproducto_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='19/04/2023 23:05:33 hs', editable=False, max_length=200),
        ),
    ]
