# Generated by Django 4.0.4 on 2022-09-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_tipoproducto_fecha_alta_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_movimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_servicio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto_vencido',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='servicio_o_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_movido',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_total',
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='10/09/2022 15:00:55 hs', editable=False, max_length=200),
        ),
    ]
