# Generated by Django 3.2.9 on 2022-09-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='15/09/2022 23:34:08 hs', editable=False, max_length=200),
        ),
    ]
